run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gocyclo
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
      text: "Function length"
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: warning