package digest

import (
	"bytes"
	"context"
	"fmt"
	"text/template"
	"time"
)

// ---------------------------------------------------------------------------
// FallbackRenderer
// ---------------------------------------------------------------------------

// FallbackRenderer produces a simplified digest when the LLM classification
// step fails. It still reports the run metadata and a list of fetched
// messages, but without classification labels or confidence scores.
type FallbackRenderer struct {
	// IncludeReadStatus controls whether the read/unread badge is shown.
	IncludeReadStatus bool

	// MaxMessageExcerpt limits the excerpt length in characters.
	MaxMessageExcerpt int
}

// compile-time check: *FallbackRenderer satisfies Renderer.
var _ Renderer = (*FallbackRenderer)(nil)

// NewFallbackRenderer creates a new FallbackRenderer with the given options.
func NewFallbackRenderer(includeReadStatus bool, maxMessageExcerpt int) *FallbackRenderer {
	return &FallbackRenderer{
		IncludeReadStatus: includeReadStatus,
		MaxMessageExcerpt: maxMessageExcerpt,
	}
}

// Name returns "fallback".
func (r *FallbackRenderer) Name() string {
	return "fallback"
}

// Render produces a fallback digest when LLM classification is unavailable.
func (r *FallbackRenderer) Render(_ context.Context, data DigestData) (string, error) {
	tmpl, err := template.New("fallback").
		Funcs(template.FuncMap{
			"formatTime": formatTime,
			"readBadge":  r.readBadge,
			"truncate":   r.truncate,
			"add1":       func(n int) int { return n + 1 },
			"now":        time.Now,
		}).
		Parse(fallbackTemplate)
	if err != nil {
		return "", fmt.Errorf("digest.fallback.parse_template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, map[string]any{
		"RunID":        data.RunID,
		"GeneratedAt":  data.GeneratedAt,
		"AccountLabel": data.AccountLabel,
		"TotalFetched": data.TotalFetched,
		"Messages":     data.Messages,
		"TotalMessages": len(data.Messages),
		"IncludeReadStatus": r.IncludeReadStatus,
	}); err != nil {
		return "", fmt.Errorf("digest.fallback.execute: %w", err)
	}

	return buf.String(), nil
}

// readBadge returns a short string indicating the read/unread status.
func (r *FallbackRenderer) readBadge(isRead bool) string {
	if !r.IncludeReadStatus {
		return ""
	}
	if isRead {
		return "✅ Read"
	}
	return "🆕 Unread"
}

// truncate shortens a string to the configured maximum length.
func (r *FallbackRenderer) truncate(s string) string {
	if r.MaxMessageExcerpt <= 0 || len(s) <= r.MaxMessageExcerpt {
		return s
	}
	return s[:r.MaxMessageExcerpt] + "…"
}

// ---------------------------------------------------------------------------
// Template
// ---------------------------------------------------------------------------

// fallbackTemplate is the template used when LLM classification failed.
// It lists all fetched messages without classification data.
const fallbackTemplate = `# ⚠️ Email Digest (Fallback)

**Run ID:** {{.RunID}}
**Generated:** {{formatTime .GeneratedAt}}
{{- if .AccountLabel}}
**Account:** {{.AccountLabel}}
{{- end}}
**Status:** ⚠️ LLM classification was unavailable — messages are listed without labels.

---

## Fetched Messages ({{.TotalMessages}})

{{- range $i, $entry := .Messages}}
### {{$i | add1}}. {{$entry.Subject}}

**From:** {{$entry.From}} | **Date:** {{formatTime $entry.Date}}
{{- if $.IncludeReadStatus}}
**Status:** {{readBadge $entry.IsRead}}
{{- end}}

> {{truncate $entry.Excerpt}}

{{- end}}

---

*Generated by Email AI Agent (fallback mode)*
`

